// ─── Categories ───────────────────────────────────────────────────────────────
export const categories = [
  { id: 'sarees', name: 'Sarees', nameTa: 'சேலைகள்', icon: '🥻', count: 248 },
  { id: 'readymade', name: 'Readymade', nameTa: 'ரெடிமேட்', icon: '👗', count: 156 },
  { id: 'javuli', name: 'Javuli', nameTa: 'ஜவுளி', icon: '🧵', count: 94 },
  { id: 'blouse', name: 'Blouse Material', nameTa: 'ரவிக்கை', icon: '✂️', count: 72 },
  { id: 'accessories', name: 'Accessories', nameTa: 'துணைப்பொருட்கள்', icon: '💍', count: 45 },
];

// ─── Saree Types ──────────────────────────────────────────────────────────────
export const sareeTypes = [
  'Kanjivaram', 'Banarasi', 'Chanderi', 'Mysore Silk', 'Tussar',
  'Patola', 'Pochampally', 'Gadwal', 'Venkatagiri', 'Dharmavaram',
  'Uppada', 'Tant', 'Sambalpuri', 'Paithani'
];

export const occasions = [
  'Wedding', 'Festival', 'Party', 'Casual', 'Office', 'Bridal'
];

export const colors = [
  { name: 'Red', hex: '#C8102E' },
  { name: 'Gold', hex: '#C9952A' },
  { name: 'Green', hex: '#1B5E20' },
  { name: 'Blue', hex: '#0D1B3E' },
  { name: 'Purple', hex: '#6A1B9A' },
  { name: 'Pink', hex: '#E91E8C' },
  { name: 'Orange', hex: '#E65100' },
  { name: 'Black', hex: '#1A1A2E' },
  { name: 'Ivory', hex: '#FBF7F0' },
  { name: 'Maroon', hex: '#6B0F1A' },
];

// ─── Products ─────────────────────────────────────────────────────────────────
export const products = [
  // SAREES
  {
    id: 1,
    name: 'Kanjivaram Pure Silk Saree',
    nameTa: 'காஞ்சிபுரம் பட்டுச்சேலை',
    category: 'sarees',
    type: 'Kanjivaram',
    occasion: 'Wedding',
    price: 12500,
    originalPrice: 16000,
    discount: 22,
    colors: ['Red', 'Gold'],
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&q=80',
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&q=80',
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&q=80',
    ],
    video: null,
    isNew: false,
    isFeatured: true,
    isBestseller: true,
    inStock: true,
    stockCount: 8,
    rating: 4.8,
    reviewCount: 124,
    description: 'Exquisite Kanjivaram pure silk saree with traditional zari work. Features intricate temple border designs and a rich pallu with peacock motifs.',
    details: {
      fabric: 'Pure Mulberry Silk',
      weight: '800g',
      length: '6.5 meters',
      width: '47 inches',
      zari: 'Pure Gold Zari',
      care: 'Dry clean only',
      origin: 'Kanchipuram, Tamil Nadu',
    },
    tags: ['silk', 'kanjivaram', 'wedding', 'traditional', 'zari'],
    relatedIds: [2, 3, 5, 7],
  },
  {
    id: 2,
    name: 'Banarasi Silk Saree',
    nameTa: 'பனாரஸி பட்டுச்சேலை',
    category: 'sarees',
    type: 'Banarasi',
    occasion: 'Wedding',
    price: 8900,
    originalPrice: 11000,
    discount: 19,
    colors: ['Purple', 'Gold'],
    images: [
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&q=80',
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&q=80',
    ],
    video: null,
    isNew: true,
    isFeatured: true,
    isBestseller: false,
    inStock: true,
    stockCount: 12,
    rating: 4.6,
    reviewCount: 89,
    description: 'Luxurious Banarasi silk saree with intricate brocade work and fine gold thread weaving throughout the fabric.',
    details: {
      fabric: 'Pure Banarasi Silk',
      weight: '750g',
      length: '6.5 meters',
      width: '47 inches',
      zari: 'Silver & Gold Zari',
      care: 'Dry clean only',
      origin: 'Varanasi, Uttar Pradesh',
    },
    tags: ['silk', 'banarasi', 'brocade', 'wedding'],
    relatedIds: [1, 3, 6, 8],
  },
  {
    id: 3,
    name: 'Chanderi Silk Cotton Saree',
    nameTa: 'சந்தேரி பட்டு காட்டன் சேலை',
    category: 'sarees',
    type: 'Chanderi',
    occasion: 'Festival',
    price: 4200,
    originalPrice: 5500,
    discount: 24,
    colors: ['Pink', 'Gold'],
    images: [
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&q=80',
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&q=80',
    ],
    video: null,
    isNew: true,
    isFeatured: false,
    isBestseller: true,
    inStock: true,
    stockCount: 20,
    rating: 4.5,
    reviewCount: 67,
    description: 'Lightweight Chanderi silk cotton saree perfect for festive occasions. Features delicate motifs and a sheer, elegant drape.',
    details: {
      fabric: 'Silk-Cotton Blend',
      weight: '450g',
      length: '6.3 meters',
      width: '45 inches',
      zari: 'Silver Zari',
      care: 'Gentle machine wash',
      origin: 'Chanderi, Madhya Pradesh',
    },
    tags: ['chanderi', 'festival', 'lightweight', 'cotton-silk'],
    relatedIds: [1, 4, 7, 9],
  },
  {
    id: 4,
    name: 'Mysore Pure Silk Saree',
    nameTa: 'மைசூர் தூய பட்டுச்சேலை',
    category: 'sarees',
    type: 'Mysore Silk',
    occasion: 'Party',
    price: 6800,
    originalPrice: 8200,
    discount: 17,
    colors: ['Blue', 'Gold'],
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&q=80',
    ],
    video: null,
    isNew: false,
    isFeatured: true,
    isBestseller: false,
    inStock: true,
    stockCount: 5,
    rating: 4.7,
    reviewCount: 45,
    description: 'Classic Mysore silk saree known for its soft texture and subtle sheen. Perfect for elegant evening gatherings.',
    details: {
      fabric: 'Pure Mysore Silk',
      weight: '600g',
      length: '6.5 meters',
      width: '47 inches',
      zari: 'Antique Gold Zari',
      care: 'Dry clean only',
      origin: 'Mysuru, Karnataka',
    },
    tags: ['mysore', 'silk', 'party', 'elegant'],
    relatedIds: [1, 2, 5, 8],
  },
  {
    id: 5,
    name: 'Dharmavaram Silk Saree',
    nameTa: 'தர்மாவரம் பட்டுச்சேலை',
    category: 'sarees',
    type: 'Dharmavaram',
    occasion: 'Wedding',
    price: 9500,
    originalPrice: 12000,
    discount: 21,
    colors: ['Maroon', 'Gold'],
    images: [
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&q=80',
    ],
    video: null,
    isNew: false,
    isFeatured: true,
    isBestseller: true,
    inStock: true,
    stockCount: 15,
    rating: 4.9,
    reviewCount: 203,
    description: 'Premium Dharmavaram silk saree with traditional South Indian motifs and heavy zari work. A bridal favorite.',
    details: {
      fabric: 'Pure Dharmavaram Silk',
      weight: '900g',
      length: '6.5 meters',
      width: '47 inches',
      zari: 'Pure Gold Zari',
      care: 'Dry clean only',
      origin: 'Dharmavaram, Andhra Pradesh',
    },
    tags: ['dharmavaram', 'bridal', 'wedding', 'heavy-zari'],
    relatedIds: [1, 2, 4, 6],
  },
  {
    id: 6,
    name: 'Patola Ikat Silk Saree',
    nameTa: 'பட்டோலா இக்கட் பட்டுச்சேலை',
    category: 'sarees',
    type: 'Patola',
    occasion: 'Festival',
    price: 15000,
    originalPrice: 18500,
    discount: 19,
    colors: ['Red', 'Blue', 'Gold'],
    images: [
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&q=80',
    ],
    video: null,
    isNew: true,
    isFeatured: true,
    isBestseller: false,
    inStock: true,
    stockCount: 3,
    rating: 4.8,
    reviewCount: 56,
    description: 'Rare double ikat Patola silk saree with geometric patterns. Each piece takes months to weave.',
    details: {
      fabric: 'Pure Patola Silk',
      weight: '700g',
      length: '6.5 meters',
      width: '45 inches',
      zari: 'No Zari (Natural Dye)',
      care: 'Dry clean only',
      origin: 'Patan, Gujarat',
    },
    tags: ['patola', 'ikat', 'handwoven', 'rare'],
    relatedIds: [1, 5, 7, 10],
  },
  {
    id: 7,
    name: 'Tussar Silk Saree',
    nameTa: 'தஸ்ஸார் பட்டுச்சேலை',
    category: 'sarees',
    type: 'Tussar',
    occasion: 'Casual',
    price: 3200,
    originalPrice: 4000,
    discount: 20,
    colors: ['Ivory', 'Gold'],
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&q=80',
    ],
    video: null,
    isNew: false,
    isFeatured: false,
    isBestseller: false,
    inStock: true,
    stockCount: 25,
    rating: 4.3,
    reviewCount: 38,
    description: 'Natural tussar silk saree with earthy tones and textured weave. Eco-friendly and sustainable.',
    details: {
      fabric: 'Natural Tussar Silk',
      weight: '500g',
      length: '6.3 meters',
      width: '45 inches',
      zari: 'No Zari',
      care: 'Gentle hand wash',
      origin: 'Bhagalpur, Bihar',
    },
    tags: ['tussar', 'casual', 'natural', 'eco-friendly'],
    relatedIds: [3, 4, 8, 9],
  },
  {
    id: 8,
    name: 'Paithani Silk Saree',
    nameTa: 'பைதானி பட்டுச்சேலை',
    category: 'sarees',
    type: 'Paithani',
    occasion: 'Wedding',
    price: 18000,
    originalPrice: 22000,
    discount: 18,
    colors: ['Green', 'Gold'],
    images: [
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&q=80',
    ],
    video: null,
    isNew: true,
    isFeatured: true,
    isBestseller: false,
    inStock: true,
    stockCount: 4,
    rating: 5.0,
    reviewCount: 29,
    description: 'Heirloom quality Paithani silk saree with peacock and lotus motifs in pure zari. A masterpiece of Maharashtra weaving.',
    details: {
      fabric: 'Pure Paithani Silk',
      weight: '850g',
      length: '6.5 meters',
      width: '47 inches',
      zari: 'Pure Zari',
      care: 'Dry clean only',
      origin: 'Paithan, Maharashtra',
    },
    tags: ['paithani', 'bridal', 'heirloom', 'peacock'],
    relatedIds: [1, 5, 6, 10],
  },
  // READYMADE
  {
    id: 9,
    name: 'Silk Salwar Kameez Set',
    nameTa: 'பட்டு சல்வார் கமீஸ் செட்',
    category: 'readymade',
    type: 'Salwar Set',
    occasion: 'Party',
    price: 2800,
    originalPrice: 3500,
    discount: 20,
    colors: ['Blue', 'Gold'],
    images: [
      'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&q=80',
      'https://images.unsplash.com/photo-1532453288672-3a27e9be9efd?w=600&q=80',
    ],
    video: null,
    isNew: true,
    isFeatured: false,
    isBestseller: true,
    inStock: true,
    stockCount: 18,
    rating: 4.4,
    reviewCount: 76,
    description: 'Ready-to-wear silk salwar kameez set with dupatta. Available in multiple sizes.',
    details: {
      fabric: 'Art Silk',
      sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      pieces: '3 Piece Set',
      care: 'Dry clean / gentle wash',
      origin: 'Made in India',
    },
    tags: ['readymade', 'salwar', 'party', 'set'],
    relatedIds: [10, 11, 12],
  },
  {
    id: 10,
    name: 'Anarkali Silk Gown',
    nameTa: 'அனார்கலி பட்டு கவுன்',
    category: 'readymade',
    type: 'Anarkali',
    occasion: 'Festival',
    price: 3600,
    originalPrice: 4200,
    discount: 14,
    colors: ['Red', 'Gold'],
    images: [
      'https://images.unsplash.com/photo-1532453288672-3a27e9be9efd?w=600&q=80',
    ],
    video: null,
    isNew: false,
    isFeatured: true,
    isBestseller: false,
    inStock: true,
    stockCount: 10,
    rating: 4.6,
    reviewCount: 55,
    description: 'Elegant floor-length Anarkali gown in rich silk fabric with embroidered yoke and flared skirt.',
    details: {
      fabric: 'Pure Silk',
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      pieces: '2 Piece Set',
      care: 'Dry clean only',
      origin: 'Made in India',
    },
    tags: ['anarkali', 'readymade', 'gown', 'festival'],
    relatedIds: [9, 11, 12],
  },
  // JAVULI (Fabric by meter)
  {
    id: 11,
    name: 'Kanjivaram Silk Fabric',
    nameTa: 'காஞ்சிபுரம் பட்டு துணி',
    category: 'javuli',
    type: 'Silk Fabric',
    occasion: 'Blouse',
    price: 1200,
    originalPrice: 1500,
    discount: 20,
    colors: ['Red', 'Green', 'Blue'],
    images: [
      'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=600&q=80',
    ],
    video: null,
    isNew: false,
    isFeatured: false,
    isBestseller: true,
    inStock: true,
    stockCount: 50,
    rating: 4.7,
    reviewCount: 92,
    description: 'Pure Kanjivaram silk fabric sold per meter. Ideal for blouses, cholis, and custom garments.',
    details: {
      fabric: 'Pure Kanjivaram Silk',
      priceUnit: 'per meter',
      width: '47 inches',
      care: 'Dry clean',
      origin: 'Kanchipuram, Tamil Nadu',
    },
    tags: ['fabric', 'silk', 'kanjivaram', 'blouse'],
    relatedIds: [12, 1, 5],
  },
  {
    id: 12,
    name: 'Banarasi Brocade Fabric',
    nameTa: 'பனாரஸி ப்ரோகேட் துணி',
    category: 'javuli',
    type: 'Brocade Fabric',
    occasion: 'Blouse',
    price: 950,
    originalPrice: 1200,
    discount: 21,
    colors: ['Gold', 'Maroon'],
    images: [
      'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=600&q=80',
    ],
    video: null,
    isNew: true,
    isFeatured: false,
    isBestseller: false,
    inStock: true,
    stockCount: 35,
    rating: 4.5,
    reviewCount: 43,
    description: 'Premium Banarasi brocade fabric with traditional motifs. Per meter pricing for custom tailoring.',
    details: {
      fabric: 'Banarasi Brocade',
      priceUnit: 'per meter',
      width: '44 inches',
      care: 'Dry clean',
      origin: 'Varanasi, UP',
    },
    tags: ['fabric', 'brocade', 'banarasi'],
    relatedIds: [11, 2, 4],
  },
];

// ─── Live Shows ───────────────────────────────────────────────────────────────
export const liveShows = [
  {
    id: 1,
    platform: 'youtube',
    title: 'Dillo Grand Saree Collection 2026',
    description: 'Watch our latest Kanjivaram collection launch LIVE',
    embedId: 'dQw4w9WgXcQ', // Replace with real ID
    date: 'Every Saturday 6 PM',
    isLive: false,
  },
  {
    id: 2,
    platform: 'instagram',
    title: 'Instagram Live Sale',
    description: 'Exclusive deals available only during live sessions',
    embedId: null,
    date: 'Every Wednesday 5 PM',
    isLive: true,
  },
];

// ─── Coupons ──────────────────────────────────────────────────────────────────
export const validCoupons = {
  'DILLO10': { discount: 10, type: 'percent', minOrder: 2000, description: '10% off on orders above ₹2000' },
  'DILLO200': { discount: 200, type: 'flat', minOrder: 3000, description: '₹200 off on orders above ₹3000' },
  'NEWUSER': { discount: 15, type: 'percent', minOrder: 1000, description: '15% off for new users' },
  'SILK500': { discount: 500, type: 'flat', minOrder: 8000, description: '₹500 off on silk sarees above ₹8000' },
  'FESTIVAL20': { discount: 20, type: 'percent', minOrder: 5000, description: '20% off during festival season' },
};

// ─── Reviews ──────────────────────────────────────────────────────────────────
export const sampleReviews = [
  {
    id: 1,
    productId: 1,
    name: 'Priya Sundaramurthy',
    rating: 5,
    date: '2026-05-12',
    title: 'Absolutely stunning!',
    content: 'The Kanjivaram saree I ordered was exactly as described. The silk quality is exceptional and the zari work is breathtaking. Wore it for my daughter\'s wedding and received so many compliments!',
    verified: true,
    helpful: 34,
  },
  {
    id: 2,
    productId: 1,
    name: 'Lakshmi Raghunathan',
    rating: 5,
    date: '2026-04-28',
    title: 'Pure silk, pure joy',
    content: 'Dillo never disappoints. This is my 4th purchase and the quality keeps getting better. Packaging was excellent and delivery was prompt.',
    verified: true,
    helpful: 28,
  },
  {
    id: 3,
    productId: 1,
    name: 'Meena Krishnan',
    rating: 4,
    date: '2026-04-10',
    title: 'Beautiful saree',
    content: 'Lovely saree with great craftsmanship. Slightly heavier than expected but the quality is undeniable. Would recommend.',
    verified: false,
    helpful: 12,
  },
];

// ─── Announcements ────────────────────────────────────────────────────────────
export const announcements = [
  '🎉 Grand Summer Sale — Up to 40% off on all Silk Sarees!',
  '🚚 Free shipping on orders above ₹2000',
  '💎 New Kanjivaram collection just arrived!',
  '📱 Use code DILLO10 for 10% off your first order',
  '🪡 Authentic handloom fabrics — Direct from weavers',
  '⭐ Over 10,000 happy customers in Tamil Nadu',
];

// ─── Banner Slides ────────────────────────────────────────────────────────────
export const bannerSlides = [
  {
    id: 1,
    title: 'Grand Silk Saree Collection',
    titleTa: 'பட்டுச்சேலை மகா திரட்டு',
    subtitle: 'Kanjivaram • Banarasi • Mysore • Dharmavaram',
    cta: 'Shop Now',
    badge: 'New Arrivals',
    bg: 'from-dillo-red-dark to-dillo-maroon',
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1600&h=850&fit=crop&q=80',
    mobileImage: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=900&h=1400&fit=crop&q=80',
  },
  {
    id: 2,
    title: 'Cost-to-Cost Mega Sale',
    titleTa: 'விலை குறைப்பு விற்பனை',
    subtitle: 'Exclusive prices you won\'t find anywhere else',
    cta: 'Grab Deals',
    badge: 'Sale Up to 40%',
    bg: 'from-dillo-navy to-dillo-charcoal',
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=1600&h=850&fit=crop&q=80',
    mobileImage: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=900&h=1400&fit=crop&q=80',
  },
  {
    id: 3,
    title: 'New Readymade Collection',
    titleTa: 'புதிய ரெடிமேட் திரட்டு',
    subtitle: 'Anarkali, Salwar Sets & more — Ready to wear',
    cta: 'Explore Now',
    badge: 'Fresh Arrivals',
    bg: 'from-yellow-800 to-dillo-gold',
    image: 'https://images.unsplash.com/photo-1532453288672-3a27e9be9efd?w=1600&h=850&fit=crop&q=80',
    mobileImage: 'https://images.unsplash.com/photo-1532453288672-3a27e9be9efd?w=900&h=1400&fit=crop&q=80',
  },
];

export const formatPrice = (price) =>
  new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(price);
